# wrangler.toml (LA VERSIÓN FINAL Y CORRECTA)

name = "schemas-work"
pages_build_output_dir = ".cloudflare/pages"

# Actualiza la fecha para optar por las nuevas características,
# incluyendo la resolución automática de módulos de Node.js.
compatibility_date = "2025-10-30" 

# Mantenemos la bandera por si acaso, es una buena práctica ser explícito.
compatibility_flags = ["nodejs_compat"]