/**
 * @file GenerateCardsCommand.ts
 * @class
 * @description
 * Command to generate study cards from document content.
 */

import { i18n } from '$lib/utils/i18n.svelte';
import { toast } from 'svelte-sonner';
import { z } from 'zod';
import * as errorService from '$lib/core/services/errorService';

import type { IAICommand, WorkbenchState } from './IAICommand';
import type { StrategySessionContext } from '$lib/modules/command-bar/ui/commandBarStore.svelte';
import * as aiSchemas from '$lib/modules/ai/domain/aiSchemas';
import * as Prompts from '$lib/modules/ai/prompts';
import { documentState } from '$lib/modules/editor/ui/documentStore.svelte';
import * as cardService from '$lib/modules/study/domain/cardService';
import type { SRS } from '$lib/types';

/**
 * Command to generate spaced repetition study cards from document content.
 * It uses the AI to extract key concepts and format them into various card types.
 */
export class GenerateCardsCommand implements IAICommand {
  /**
   * The user-facing title of the command.
   */
  public get title(): string {
    return i18n.t('ai_commands.generate_cards.title', {
      fallback: 'Generate Study Cards',
    });
  }

  /**
   * The Zod schema used to validate the AI's response.
   * Ensures the output is a valid array of card objects.
   */
  public readonly validationSchema = aiSchemas.FlashcardResponseSchema;

  /**
   * Generates the prompt for the card generation task.
   *
   * @param context - The context of the current strategy session, including the document text.
   * @param workbenchState - The state of the workbench (unused here, but part of the interface).
   * @param instruction - Additional user instructions (unused here).
   * @returns {string} The fully constructed prompt string.
   */
  public getPrompt(
    context: StrategySessionContext & { quantity?: number },
    workbenchState: WorkbenchState,
    instruction: string
  ): string {
    const documentText = context.fullDocumentText || '';

    const settings = {
      // Use the quantity from the UI if it's provided, otherwise default to 5.
      quantity: context.quantity ?? 5,
      // Default set of card types to generate.
      types: ['basic', 'input', 'true_false', 'multiple_choice'] as SRS.CardType[],
    };

    return Prompts.getGenerateCardsPrompt(settings, documentText);
  }

  /**
   * Handles the successful, validated response from the AI by saving the new cards.
   *
   * @param result - The validated array of new cards generated by the AI.
   * @param context - The context of the session (unused here).
   * @returns {Promise<void>}
   */
  public async onAccept(
    result: z.infer<typeof this.validationSchema>,
    context: StrategySessionContext
  ): Promise<void> {
    const docId = documentState.docId;

    if (!docId) {
      toast.error(
        i18n.t('ai_commands.generate_cards.error_no_doc', {
          fallback:
            'Save Error: Could not find the active document ID to save cards to.',
        })
      );
      return;
    }
    if (!result || result.length === 0) {
      toast.info(
        i18n.t('ai_commands.generate_cards.info_no_cards', {
          fallback: 'The AI did not generate any cards.',
        })
      );
      return;
    }

    try {
      await cardService.addCards(docId, result as SRS.NewCard[]);
      const successMessage = i18n.t('ai_commands.generate_cards.success', {
        count: result.length,
      });
      toast.success(
        successMessage ||
          `${result.length} new study card(s) created successfully.`
      );
    } catch (error) {
      errorService.reportError(error as Error, {
        context: 'GenerateCardsCommand',
        action: 'onAccept',
      });
      toast.error(
        i18n.t('ai_commands.generate_cards.error_critical', {
          fallback:
            'A critical error occurred while trying to save the new cards.',
        })
      );
    }
  }
}
