/**
 * @file CreateSchemaCommand.ts
 * @class
 * @description
 * Implements the "Create Document from Text" command for the AI Workbench.
 * This command takes unstructured text input and uses the AI to generate a
 * structured, hierarchical Tiptap document (schema).
 */

import type { IAICommand, WorkbenchState } from './IAICommand';
import {
  type StrategySessionContext,
  commandBarState,
} from '$lib/modules/command-bar/ui/commandBarStore.svelte';
import { create as createDocument } from '$lib/stores/documentStore.svelte';
import * as aiSchemas from '$lib/schemas/aiSchemas';
import * as Prompts from '$lib/services/ai/prompts';
import { toast } from 'svelte-sonner';
import { i18n } from '$lib/utils/i18n.svelte';
import type { z } from 'zod';

/**
 * Command to create a new, structured document from raw text input.
 */
export class CreateSchemaCommand implements IAICommand {
  /**
   * The user-facing title of the command.
   */
  public get title(): string {
    return i18n.t('ai_commands.create_schema.title', {
      default: 'Create Document from Text',
    });
  }

  /**
   * The Zod schema used to validate the AI's response.
   * Ensures the output is a valid Tiptap document structure.
   */
  public readonly validationSchema = aiSchemas.CreateSchemaAiResponseSchema;

  /**
   * Generates the prompt for the schema creation task.
   *
   * @param context - The session context containing the initial user input.
   * @param workbenchState - The workbench state (unused).
   * @param instruction - Additional instructions (unused).
   * @returns {string} The prompt string.
   */
  public getPrompt(
    context: StrategySessionContext,
    workbenchState: WorkbenchState,
    instruction: string
  ): string {
    const rawText = context.initialInput || '';
    return Prompts.getCreateSchemaPrompt({}, rawText);
  }

  /**
   * Handles the successful, validated response from the AI by creating a new document.
   *
   * @param result - The valid Tiptap JSON content generated by the AI.
   * @param context - The session context (unused).
   * @returns {Promise<void>}
   */
  public async onAccept(
    result: z.infer<typeof this.validationSchema>,
    context: StrategySessionContext
  ): Promise<void> {
    const defaultTitle = i18n.t('ai_commands.create_schema.default_title', {
      default: 'New Schema',
    });

    // Extract the title from the first H1 heading, if present.
    const title = result.content?.[0]?.content?.[0]?.text || defaultTitle;
    const parentId = commandBarState.viewPayload?.parentId || null;

    createDocument(title, result, parentId);

    const messageTemplate = i18n.t('ai_commands.create_schema.success', {
      default: "Document '{title}' created successfully.",
    });
    const finalMessage = messageTemplate.replace('{title}', title);

    toast.success(finalMessage);
  }
}
