/**
 * @file GenerateFormulaCommand.ts
 * @class
 * @description
 * Implements the "Create Formula from Description" command.
 * This command allows users to describe a mathematical formula in plain English,
 * and the AI converts it into a valid KaTeX string for insertion into the editor.
 */

import type { IAICommand, WorkbenchState } from './IAICommand';
import { type StrategySessionContext } from '$lib/modules/command-bar/ui/commandBarStore.svelte';
import * as Prompts from '$lib/services/ai/prompts';
import { editorState } from '$lib/modules/editor/ui/editorStore.svelte';
import { z } from 'zod';

/**
 * Command to generate a mathematical formula from a natural language description.
 */
export class GenerateFormulaCommand implements IAICommand {
  public title = 'Create Formula from Description';

  /**
   * Description shown in the UI helper.
   */
  public description =
    'Describe a math formula in plain text, and the AI will generate the KaTeX for it.';

  /**
   * Placeholder text for the input field.
   */
  public placeholder =
    'e.g., "The Pythagorean theorem" or "The standard deviation formula"';

  /**
   * The validation schema. The AI should return a single non-empty string containing the KaTeX formula.
   */
  public readonly validationSchema = z.string().min(1);

  /**
   * Generates the prompt for the formula generation task.
   *
   * @param context - The session context (unused).
   * @param workbenchState - The workbench state (unused).
   * @param instruction - The user's description of the formula (e.g., "Area of a circle").
   * @returns {string} The prompt string.
   */
  public getPrompt(
    context: StrategySessionContext,
    workbenchState: WorkbenchState,
    instruction: string
  ): string {
    return Prompts.getGenerateFormulaPrompt(instruction);
  }

  /**
   * Handles the successful response from the AI by inserting the formula into the editor.
   *
   * @param result - The KaTeX string generated by the AI.
   * @param context - The session context (unused).
   * @returns {Promise<void>}
   */
  public async onAccept(
    result: z.infer<typeof this.validationSchema>,
    context: StrategySessionContext
  ): Promise<void> {
    const editor = editorState.instance;
    if (!editor) return;

    // `result` is the clean KaTeX string, e.g., "E = mc^2"
    const formula = result;

    // Use Tiptap's command chain to insert a new math node at the user's cursor position.
    editor
      .chain()
      .focus()
      .insertContent({
        type: 'math_inline', // TODO: Consider adding logic to choose between inline/block based on length or context.
        attrs: {
          formula: formula,
        },
      })
      .run();
  }
}
