/**
 * @file service-worker.ts
 * @description
 * The Service Worker implementation for Progressive Web App (PWA) capabilities.
 *
 * This script runs in the background, separate from the main web page, and handles:
 * - **Offline Caching:** Pre-caches all static assets generated by SvelteKit during the build.
 * - **Network Proxying:** Intercepts network requests to serve content from the cache when offline (Cache First strategy).
 * - **Cache Management:** Automatically deletes old caches when a new version of the app is deployed.
 *
 * It uses the `$service-worker` module provided by SvelteKit to access the list of build artifacts.
 */

/// <reference lib="webworker" />
/// <reference types="vite/client" />

import { build, files, version } from '$service-worker';

/**
 * The unique identifier for the current cache version.
 * Including the version ensures that every new deployment creates a fresh cache.
 */
const CACHE_NAME = `schemas-work-cache-${version}`;

/**
 * The list of all URLs to be pre-cached immediately upon installation.
 * Includes:
 * - `/`: The root entry point (essential for SPA navigation).
 * - `...build`: JavaScript and CSS bundles generated by Vite.
 * - `...files`: Static assets in the `static/` directory (images, favicon, etc.).
 */
const ASSETS_TO_CACHE: string[] = ['/', ...build, ...files];

// --- EVENT LISTENERS ---

/**
 * INSTALL Event
 * Triggered when the browser installs the service worker.
 * We use this opportunity to open the cache and download all critical assets.
 */
self.addEventListener('install', (event) => {
  const installEvent = event as ExtendableEvent;
  installEvent.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[ServiceWorker] Pre-caching all static assets.');
      return cache.addAll(ASSETS_TO_CACHE);
    })
  );
});

/**
 * ACTIVATE Event
 * Triggered when the new service worker takes control.
 * We use this to clean up any old caches from previous versions to free up storage space.
 */
self.addEventListener('activate', (event) => {
  const activateEvent = event as ExtendableEvent;
  activateEvent.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((oldKey) => {
            console.log(`[ServiceWorker] Deleting old cache: ${oldKey}`);
            return caches.delete(oldKey);
          })
      )
    )
  );
});

/**
 * FETCH Event
 * Triggered for every network request made by the app.
 * Implements a "Cache First, Network Fallback" strategy for assets,
 * and robust offline fallbacks for navigation.
 */
self.addEventListener('fetch', (event) => {
  const fetchEvent = event as FetchEvent;
  const request = fetchEvent.request;

  // We only handle GET requests; let the browser handle POST/PUT/etc.
  if (request.method !== 'GET') {
    return;
  }

  // The core fetch handler logic
  async function respond(): Promise<Response> {
    const cache = await caches.open(CACHE_NAME);

    // 1. Cache Hit: Return the cached response immediately if found.
    const cachedResponse = await cache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }

    // 2. Cache Miss: Attempt to fetch from the network.
    try {
      const networkResponse = await fetch(request);

      // If the fetch was successful and is for an asset on our own domain,
      // cache a copy for next time.
      if (request.url.startsWith(self.location.origin)) {
        await cache.put(request, networkResponse.clone());
      }

      return networkResponse;
    } catch (error) {
      // 3. Offline Fallback: If network fails (user is offline)...

      // If the user is trying to navigate to a page (HTML request),
      // serve the cached root page (Single Page App shell).
      if (request.mode === 'navigate') {
        const rootFallback = await cache.match('/');
        if (rootFallback) {
          return rootFallback;
        }
      }

      // For all other failed requests (like API calls or missing images),
      // return a generic 503 response.
      return new Response('Offline', {
        status: 503,
        statusText: 'Service Unavailable',
        headers: { 'Content-Type': 'text/plain' },
      });
    }
  }

  fetchEvent.respondWith(respond());
});
